nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(resolve:CORS_ALLOW_ORIGIN)%', 'http://localhost:4200']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Origin']
        expose_headers: ['Link']
        max_age: 3600


